import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import Header from "./components/Header/Header";
import Providers from "./components/WagmiProvider"; // Import the Provider component
import { NextUIProvider } from "@nextui-org/react";

const suisseIntl = localFont({
  src: [
    {
      path: "./fonts/SuisseIntl-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SuisseIntl-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-suisse-intl",
});

export const metadata = {
  title: "DeESG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/app_logo.png" />
      </Head>
      <body className={`${suisseIntl.variable} antialiased bg-[#faeed4] min-h-[100vh]` }>
        <NextUIProvider>
          <Providers>
            <Header />
            {children}
          </Providers>
        </NextUIProvider>
      </body>
    </html>
  );
}
