  import localFont from "next/font/local";
  import "./globals.css";
  import Head from "next/head";
  import Header from "./components/Header/Header";
  import Footer from "./components/Footer/footer";
  import Providers from "./components/WagmiProvider"; 
  import { NextUIProvider } from "@nextui-org/react";


  const suisseIntl = localFont({
    src: [
      {
        path: "./fonts/SuisseIntl-Regular.woff2",
        weight: "400",
        style: "normal",
      },
      {
        path: "./fonts/SuisseIntl-Bold.woff2",
        weight: "700",
        style: "normal",
      },
    ],
    variable: "--font-suisse-intl",
  });

  export const metadata = {
    title: "DeESG",
    description: "Generated by create next app",
    icons: {
      icon: "/app_logo.png", 
    },
  };

  export default function RootLayout({ children }) {
    return (
      <html lang="en" className="h-full">
        <head>
          <link rel="icon" href="/app_logo.png" />
        </head>
        <body className="flex flex-col h-full min-h-screen antialiased bg-[#f6f6f6]">
          <NextUIProvider>
            <Providers>
              <Header />
              <div className="flex-grow">{children}</div>
              <Footer />
            </Providers>
          </NextUIProvider>
        </body>
      </html>
    );
  }
