import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/footer";
import Providers from "./components/WagmiProvider";
import { NextUIProvider } from "@nextui-org/react";
import { Instrument_Sans } from 'next/font/google';

const suisseIntl = localFont({
  src: [
    {
      path: "./fonts/SuisseIntl-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SuisseIntl-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/VCR_OSD_MONO_1.001.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-suisse-intl",
});

const instrumentSans = Instrument_Sans({
  subsets: ['latin'],
  variable: '--font-instrument-sans',
});

export const metadata = {
  title: "DeESG",
  description: "Generated by create next app",
  icons: {
    icon: "/app_logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${instrumentSans.variable}`}>
      <Head>
        <link rel="icon" href="/app_logo.png" />
      </Head>
      <body
        className={`${suisseIntl.variable} antialiased bg-[#f6f6f6] min-h-[100vh] flex flex-col`}
      >
        <NextUIProvider>
          <Providers>
            <Header />
            {children}
          </Providers>
        </NextUIProvider>
        <Footer />
      </body>
    </html>
  );
}
