type = "directrequest"
schemaVersion = 1
name = "Fetch and Store Aggregated ESG Data From AI"
externalJobID = "8c08e276-ff4d-43ab-bc5e-1ab07d9f5556"
forwardingAllowed = false
maxTaskDuration = "15m0s"
contractAddress = "0xE7874B2C5743E62F22b47DDA94596aEbe8aCbC31"
evmChainID = "11155111"
minIncomingConfirmations = 1
minContractPaymentLinkJuels = "100000000000000"
observationSource = """
    fetch_data [type=http
        method="POST"
        url="http://84.247.151.195:8082/"
        requestData="{\\"id\\":\\"test-job\\"}"
        allowunrestrictednetworkaccess="true"
    ]

    parse_cluster [type=jsonparse
        data="$(fetch_data)"
        path="data,aggregatedCluster"
    ]

    parse_esg_score [type=jsonparse
        data="$(fetch_data)"
        path="data,aggregatedESGScore"
    ]

    parse_risk_category [type=jsonparse
        data="$(fetch_data)"
        path="data,mostCommonRiskCategory"
    ]

   encode_data [type=ethabiencode
        abi="storeAggregatedData(uint256 _aggregatedCluster, string _aggregatedESGScore, string _mostCommonRiskCategory)"
        data="{\\"_aggregatedCluster\\": $(parse_cluster), \\"_aggregatedESGScore\\": $(parse_esg_score), \\"_mostCommonRiskCategory\\": $(parse_risk_category)}"
    ]

    call_contract [type=ethtx
        to="0x4861A975A8F535414672Ecb883B546E035564445"
        data="$(encode_data)"
        evmChainID="11155111"
        gasLimit="800000"
        failOnRevert="false"
        extractResult="true"
    ]

    fetch_data -> parse_cluster -> parse_esg_score -> parse_risk_category -> encode_data -> call_contract
"""