type = "directrequest"
schemaVersion = 1
name = "Fetch and Store Emission Data Linea"
externalJobID = "4c08e276-ff4d-43ab-bc5e-1ab07d9f5555"
forwardingAllowed = false
maxTaskDuration = "15m0s"
contractAddress = "0xE7874B2C5743E62F22b47DDA94596aEbe8aCbC31"
evmChainID = "11155111"
minIncomingConfirmations = 1
minContractPaymentLinkJuels = "100000000000000"
observationSource = """
   fetch_data [type=http
        method="POST"
        url="http://84.247.151.195:8081/"
        requestData="{\\"id\\":\\"test1234\\"}"
        allowunrestrictednetworkaccess="true"
    ]

    parse_CO2 [type=jsonparse
        data="$(fetch_data)"
        path="data,CO2_emissions"
    ]

    parse_methane [type=jsonparse
        data="$(fetch_data)"
        path="data,methane_emissions"
    ]

    parse_NOx [type=jsonparse
        data="$(fetch_data)"
        path="data,NOx_emissions"
    ]

    parse_PM [type=jsonparse
        data="$(fetch_data)"
        path="data,PM_emissions"
    ]

    parse_humidity [type=jsonparse
        data="$(fetch_data)"
        path="data,humidity"
    ]

    parse_temperature [type=jsonparse
        data="$(fetch_data)"
        path="data,temperature"
    ]

    encode_data [type=ethabiencode
        abi="storeDataAndReward(uint256 _CO2_emissions, uint256 _methane_emissions, uint256 _NOx_emissions, uint256 _PM_emissions, uint256 _humidity, uint256 _temperature)"
        data="{\\"_CO2_emissions\\": $(parse_CO2), \\"_methane_emissions\\": $(parse_methane), \\"_NOx_emissions\\": $(parse_NOx), \\"_PM_emissions\\": $(parse_PM), \\"_humidity\\": $(parse_humidity), \\"_temperature\\": $(parse_temperature)}"
    ]

    call_contract [type=ethtx
        to="0x8bBD2C66Ea415de7cdA73C481520e4f1cb40c365"
        data="$(encode_data)"
        evmChainID="59141"
        gasLimit="500000"
        failOnRevert="false"
        extractResult="true"
    ]

    fetch_data -> parse_CO2 -> parse_methane -> parse_NOx -> parse_PM -> parse_humidity -> parse_temperature -> encode_data -> call_contract
"""