type = "directrequest"
schemaVersion = 1
name = "Fetch and Store Aggregated ESG Data From AI Sepolia"
externalJobID = "1c08e276-ff4d-43ab-bc5e-1ab07d9f5556"
forwardingAllowed = false
maxTaskDuration = "15m0s"
contractAddress = "0xb3DCb1123C23432c9a93632D808c3Ddd03069a88"
evmChainID = "11155111"
minIncomingConfirmations = 1
minContractPaymentLinkJuels = "100000000000000"
observationSource = """
    fetch_data [type=http
        method="POST"
        url="http://84.247.151.195:8082/"
        requestData="{\\"id\\":\\"job6\\"}"
        allowunrestrictednetworkaccess="true"
    ]

    parse_cluster [type=jsonparse
        data="$(fetch_data)"
        path="data,aggregatedCluster"
    ]

    parse_esg_score [type=jsonparse
        data="$(fetch_data)"
        path="data,aggregatedESGScore"
    ]

    parse_risk_category [type=jsonparse
        data="$(fetch_data)"
        path="data,mostCommonRiskCategory"
    ]

   encode_data [type=ethabiencode
        abi="storeAggregatedData(uint256 _aggregatedCluster, string _aggregatedESGScore, string _mostCommonRiskCategory)"
        data="{\\"_aggregatedCluster\\": $(parse_cluster), \\"_aggregatedESGScore\\": $(parse_esg_score), \\"_mostCommonRiskCategory\\": $(parse_risk_category)}"
    ]

    call_contract [type=ethtx
        to="0xF96Def7ec929b95A63DBfD456Cf04d22164F11a0"
        data="$(encode_data)"
        evmChainID="11155111"
        gasLimit="800000"
        failOnRevert="false"
        extractResult="true"
    ]

    fetch_data -> parse_cluster -> parse_esg_score -> parse_risk_category -> encode_data -> call_contract
"""